### ISSUE TITLE
Incorrect LICENSE field value

### ISSUE THREAD

**Issue by paddy-hack** [sirjaren/gentoo-overlay#3]
Your `epson-ds-3.13.0.ebuild` mentions
```
LICENSE="AVASYS"
```
Considering that the copyright for the bulk of the code is held by SEIKO EPSON CORPORATION, I believe that AVASYS is incorrect.

**Comment by sirjaren** [comment]
Hey paddy-hack,

For both `imagescan-0.13.0` and `utsushi-0.13.0`, the `COPYING` file mentions the GPL-3 as the license for the driver.  Should I go ahead and use that for the `epson-ds-3.13.0.ebuld`?

For `epson-ds-plugins-1.0.3.ebuild`, I chose the AVASYS license since the `README` mentions the AVASYS PUBLIC LICENSE under the LICENSING header.  Additionally, the packages provides both the English and Japanese translations of the license (`AVASYSPL.en.txt` and `AVASYSPL.ja.txt`).

I found three different licenses that `Gentoo` is aware of that would apply to Epson:
<pre>
<b>$ grep -lEir 'epson|avasys' /usr/portage/licenses</b>
/usr/portage/licenses/EAPL
/usr/portage/licenses/AVASYS
/usr/portage/licenses/EPSON
</pre>

To summarize, this is what I'm thinking:
`epson-ds-3.13.0.ebuild`: GPL-3
`epson-ds-plugins-1.0.3.ebuild`: AVASYS

Based on the information in the licenses above:
<pre>
<b>$ head -n5 /usr/portage/licenses/EAPL /usr/portage/licenses/AVASYS /usr/portage/licenses/EPSON</b>
==> /usr/portage/licenses/EAPL <==

                     EPSON AVASYS PUBLIC LICENSE
                              2005-04-01

  This License applies to any program or other work identified as such

==> /usr/portage/licenses/AVASYS <==

                        AVASYS PUBLIC LICENSE
                              2008-04-01

  This License applies to any program or other work identified as such

==> /usr/portage/licenses/EPSON <==
SEIKO EPSON CORPORATION
SOFTWARE LICENSE AGREEMENT

IMPORTANT! READ THIS SOFTWARE LICENSE AGREEMENT CAREFULLY.  The
computer software product, fontware, typefaces and/or data, including
</pre>

What do you think?

**Comment by sirjaren** [comment]
I've made changes to the `epson-ds-0.13.0.ebuild` referenced here:
39273162de7e18ce039223afb0f04601546d88bb

I'm not a license expert by any stretch of the imagination, so I'm hoping this is sufficient.  If you think otherwise, I'm all ears.

Thanks paddy-hack.

**Comment by paddy-hack** [comment]
The bulk of the *original* source files for [imagescan](https://github.com/utsushi/imagescan) (the files on the `vcfiles` branch) are GPL-3.0+.  Most files have a `License:` field in their header you can check.  The files on the `archive` branch are the full set that is in the upstream source tarballs.

Considering the above, GPL-3.0+ (or the closest that Gentoo uses that corresponds with that) would be fine for the `LICENSE` setting in `epson-ds-0.13.0.ebuild`.

I now also understand that this field refers to the type of license that applies to the software and not to the copyright holder.

For non-free software such as your `epson-ds-plugins-1.0.3.ebuild`, a `non-free` would be enough for me.  Anything more specific doesn't matter for me personally.  As for the details of its non-free license, I don't care and can't be bothered to look into it.  If you really want to know, ask where you got it.  This isn't meant to be rude.  I just will not spend my private time on non-free software, that's all.

Your changes look fine, BTW, and I consider the license issue closed.
